<?php
/**
 * Created by PhpStorm.
 * User: jmanihuariy
 * Date: 26/01/2020
 * Time: 14:39
 */

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Navigation extends Category
{
    public function scopeActive($query)
    {
        $query->where('is_navigation',1);
        return parent::scopeActive($query); // TODO: Change the autogenerated stub
    }

}
